anatomy-features:

  - name: ide-ignores
    items:

      - name: gitignore
        add-file-block:
          filename: .gitignore
          contents: |
            /.idea/
            /.project/

      - name: pytestini
        add-file-block:
          filename: pytest.ini
          contents: |
            [pytest]
            timeout = 100

  - name: python-project
    items:
      - name: gitignore
        add-file-block:
          filename: .gitignore
          contents: |
            .pyc
            .pyd
            .pyo

  - name: readme
    items:
      - name: readme
        add-file-block:
          filename: README.md
          contents: |
            # This is {{project.name}}.

            The code is at `{{project.code_name}}`.

            Global is {{global}}.
