anatomy-features:

  - name: ide-ignores
    items:

      - name: gitignore
        add-file-block:
          filename: .gitignore
          contents: |
            /.idea/
            /.project/

      - name: pytestini
        add-file-block:
          filename: pytest.ini
          contents: |
            [pytest]
            timeout = 100

  - name: python-project
    items:
      - name: gitignore
        add-file-block:
          filename: .gitignore
          contents: |
            .pyc
            .pyd
            .pyo
